"""
AI ScamShield — Intelligent Scam & Phishing Detection Agent
IBM Build on IBM (BOB) Hackathon 2025

Flask backend serving the 4-agent agentic pipeline:
    Agent 1 — Scam Type Classifier         (scam_engine.classify_scam_type)
    Agent 2 — Threat Indicator Analyzer     (scam_engine.analyze_indicators)
    Agent 3 — RAG Knowledge Retrieval       (knowledge_base.retrieve_knowledge)
    Agent 4 — Safety Advice Generator       (scam_engine.safety_tips_for / report_to_for)

Explanations, chat replies, and formal reports are generated by IBM
Granite via watsonx.ai when WATSONX_API_KEY / WATSONX_PROJECT_ID are
configured (see watsonx_client.py); otherwise the app transparently
falls back to the deterministic local engine so it always works.

Run:
    pip install -r requirements.txt
    python app.py
Then open http://localhost:5000
"""

import os
import uuid
import random
import logging
from datetime import datetime, timedelta

from flask import Flask, render_template, request, jsonify, session

import watsonx_client
from knowledge_base import retrieve_knowledge
from scam_engine import (
    classify_scam_type,
    analyze_indicators,
    determine_verdict,
    safety_tips_for,
    report_to_for,
    build_explanation_fallback,
)

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("scamshield")

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-change-me")

# ── In-memory stats store (resets on restart; swap for a DB in production) ──
STATS = {
    "date": datetime.utcnow().date(),
    "total_scans": 0,
    "scams_detected": 0,
    "phishing_blocked": 0,
    "upi_flagged": 0,
    "urls_flagged": 0,
    "by_type": {},          # scam_type -> count
    "by_risk": {"HIGH": 0, "MEDIUM": 0, "LOW": 0, "SAFE": 0},
}

CHAT_SESSIONS = {}  # session_id -> list of {role, content}


def _reset_stats_if_new_day():
    today = datetime.utcnow().date()
    if STATS["date"] != today:
        STATS.update({
            "date": today, "total_scans": 0, "scams_detected": 0,
            "phishing_blocked": 0, "upi_flagged": 0, "urls_flagged": 0,
            "by_type": {}, "by_risk": {"HIGH": 0, "MEDIUM": 0, "LOW": 0, "SAFE": 0},
        })


def _record_scan(scam_type: str, risk_level: str):
    _reset_stats_if_new_day()
    STATS["total_scans"] += 1
    if risk_level in ("HIGH", "MEDIUM"):
        STATS["scams_detected"] += 1
    if scam_type == "Phishing Email":
        STATS["phishing_blocked"] += 1
    if scam_type == "UPI Fraud":
        STATS["upi_flagged"] += 1
    if scam_type == "Malicious URL":
        STATS["urls_flagged"] += 1
    STATS["by_type"][scam_type] = STATS["by_type"].get(scam_type, 0) + 1
    STATS["by_risk"][risk_level] = STATS["by_risk"].get(risk_level, 0) + 1


# ══════════════════════════════════════════════════════════════════════════
# PAGE
# ══════════════════════════════════════════════════════════════════════════
@app.route("/")
def index():
    return render_template("index.html")


# ══════════════════════════════════════════════════════════════════════════
# API: EXAMPLES
# ══════════════════════════════════════════════════════════════════════════
EXAMPLES = [
    {
        "label": "Bank KYC Scam",
        "type": "sms",
        "text": ("Dear Customer, Your SBI account has been suspended due to KYC expiry. "
                  "Click http://sbi-verify-now.xyz within 24 hours to reactivate or your "
                  "account will be permanently blocked."),
    },
    {
        "label": "UPI Refund Trick",
        "type": "upi",
        "text": ("Hi, I accidentally sent you Rs.5000 by mistake. Please accept my UPI "
                  "collect request to receive the refund immediately, it's urgent!"),
    },
    {
        "label": "Fake Job Offer",
        "type": "job",
        "text": ("Congratulations! You are selected for a work from home data entry job. "
                  "Earn Rs.3000 per day, no experience needed. Pay Rs.499 registration fee "
                  "to activate your account and start earning today."),
    },
    {
        "label": "Lottery Winner",
        "type": "whatsapp",
        "text": ("CONGRATULATIONS! Your number has won Rs.25,00,000 in the KBC Lucky Draw "
                  "2025! To claim your prize, pay a processing fee of Rs.2,500 and share "
                  "your bank account and Aadhaar number immediately."),
    },
    {
        "label": "Phishing Email",
        "type": "email",
        "text": ("Dear valued customer, we detected unusual activity on your Amazon "
                  "account. Verify your identity now at http://amaz0n-secure-login.top or "
                  "your account will be deactivated within 12 hours."),
    },
    {
        "label": "QR Code Scam",
        "type": "qr",
        "text": ("Scan this QR code to receive your cashback of Rs.1000 from Paytm. "
                  "Offer expires today, scan QR and enter your UPI PIN to claim now."),
    },
    {
        "label": "Genuine Message",
        "type": "sms",
        "text": ("Hi, this is a reminder that your electricity bill payment of Rs.1,240 is "
                  "due on 15th July. You can pay via the official app or website."),
    },
]


@app.route("/api/examples")
def api_examples():
    return jsonify({"examples": EXAMPLES})


# ══════════════════════════════════════════════════════════════════════════
# API: ANALYZE  (Agents 1, 2, 3, 4)
# ══════════════════════════════════════════════════════════════════════════
@app.route("/api/analyze", methods=["POST"])
def api_analyze():
    body = request.get_json(silent=True) or {}
    message = (body.get("message") or "").strip()
    scan_type = body.get("type", "all")

    if not message:
        return jsonify({"error": "Message is required."}), 400
    if len(message) > 5000:
        return jsonify({"error": "Message exceeds 5000 character limit."}), 400

    # Agent 1 — classify
    scam_type = classify_scam_type(message, scan_type)

    # Agent 2 — threat indicators + risk score
    indicator_result = analyze_indicators(message)
    reasons = indicator_result["reasons"]
    score = indicator_result["score"]

    verdict, risk_level = determine_verdict(score)
    if scam_type == "No Specific Scam Pattern" and verdict == "GENUINE":
        scam_type = "None Detected"

    # Agent 3 — RAG knowledge retrieval
    knowledge = retrieve_knowledge(message, scam_type)

    # Agent 4 — safety advice
    safety_tips = safety_tips_for(scam_type)
    report_to = report_to_for(scam_type)

    # Explanation text — try Granite via watsonx, fall back to local template
    explanation = None
    cyber_guidance = None
    if watsonx_client.is_configured():
        try:
            prompt = _build_analysis_prompt(message, scam_type, verdict, risk_level, reasons, knowledge["combined_text"])
            explanation = watsonx_client.generate(prompt, max_new_tokens=300)
        except Exception as e:
            log.warning("watsonx.ai explanation generation failed, using fallback: %s", e)

    if not explanation:
        explanation = build_explanation_fallback(verdict, scam_type, reasons)
        cyber_guidance = None

    _record_scan(scam_type, risk_level)

    return jsonify({
        "verdict": verdict,
        "scam_type": scam_type,
        "risk_level": risk_level,
        "confidence": round(min(97.0, max(52.0, score + random.uniform(-3, 5))), 1),
        "explanation": explanation,
        "knowledge": knowledge["combined_text"] or "No specific knowledge-base matches found.",
        "reasons": reasons,
        "safety_tips": safety_tips,
        "report_to": report_to,
        "cyber_guidance": cyber_guidance,
        "agent_source": "IBM Granite (watsonx.ai)" if watsonx_client.is_configured() else "Local Reasoning Engine",
    })


def _build_analysis_prompt(message, scam_type, verdict, risk_level, reasons, knowledge_text):
    reasons_block = "\n".join(f"- {r}" for r in reasons) or "- None specifically flagged."
    return (
        "You are a cybersecurity analyst assistant for AI ScamShield, an Indian "
        "scam/phishing detection tool. Given the structured analysis below, write a "
        "clear, 3-4 sentence plain-language explanation for a non-technical user of "
        "why the message was classified this way. Be concrete and reference the "
        "specific red flags. Do not repeat these instructions in your answer.\n\n"
        f"Message analysed: \"{message}\"\n"
        f"Classification: {scam_type}\n"
        f"Verdict: {verdict} (Risk: {risk_level})\n"
        f"Detected indicators:\n{reasons_block}\n\n"
        f"Relevant cybersecurity knowledge base context: {knowledge_text}\n\n"
        "Explanation:"
    )


# ══════════════════════════════════════════════════════════════════════════
# API: SECURITY REPORT
# ══════════════════════════════════════════════════════════════════════════
@app.route("/api/security-report", methods=["POST"])
def api_security_report():
    body = request.get_json(silent=True) or {}
    analysis = body.get("analysis_result") or {}

    if not analysis:
        return jsonify({"error": "analysis_result is required."}), 400

    if watsonx_client.is_configured():
        try:
            prompt = _build_report_prompt(analysis)
            report = watsonx_client.generate(prompt, max_new_tokens=500)
            return jsonify({"report": report, "generated_by": "IBM Granite (watsonx.ai)"})
        except Exception as e:
            log.warning("watsonx.ai report generation failed, using fallback: %s", e)

    report = _build_report_fallback(analysis)
    return jsonify({"report": report, "generated_by": "Local Reasoning Engine"})


def _build_report_prompt(analysis):
    return (
        "You are a cybersecurity analyst. Write a formal, structured Threat "
        "Intelligence Report (with sections: Summary, Classification, Risk "
        "Assessment, Indicators, Recommended Actions) based on this scam analysis "
        "data. Keep it under 300 words, professional tone.\n\n"
        f"Data: {analysis}\n\nReport:"
    )


def _build_report_fallback(analysis):
    verdict = analysis.get("verdict", "UNKNOWN")
    scam_type = analysis.get("scam_type", "Unknown")
    risk = analysis.get("risk_level", "UNKNOWN")
    confidence = analysis.get("confidence", "N/A")
    reasons = analysis.get("reasons", [])
    tips = analysis.get("safety_tips", [])
    report_to = analysis.get("report_to", [])
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    reasons_txt = "\n".join(f"  {i+1}. {r}" for i, r in enumerate(reasons)) or "  None specifically flagged."
    tips_txt = "\n".join(f"  - {t}" for t in tips)
    report_txt = "\n".join(f"  - {a}" for a in report_to)

    return (
        f"THREAT INTELLIGENCE REPORT\n"
        f"Generated: {timestamp}\n"
        f"{'='*50}\n\n"
        f"1. SUMMARY\n"
        f"   Verdict: {verdict}  |  Risk Level: {risk}  |  Confidence: {confidence}%\n"
        f"   Classification: {scam_type}\n\n"
        f"2. THREAT INDICATORS\n{reasons_txt}\n\n"
        f"3. RECOMMENDED ACTIONS\n{tips_txt}\n\n"
        f"4. REPORT TO\n{report_txt}\n\n"
        f"{'='*50}\n"
        f"Generated by AI ScamShield Local Reasoning Engine.\n"
        f"Configure WATSONX_API_KEY / WATSONX_PROJECT_ID for IBM Granite-generated reports."
    )


# ══════════════════════════════════════════════════════════════════════════
# API: CHAT
# ══════════════════════════════════════════════════════════════════════════
CANNED_CHAT_RESPONSES = [
    (["upi", "collect request", "gpay", "phonepe"],
     "A UPI collect request asks money to be sent FROM your account — you should never "
     "enter your UPI PIN to 'receive' money. If someone asks you to approve a collect "
     "request to get a refund or cashback, it's almost always a scam. Decline it and "
     "verify with the sender through another channel."),
    (["otp", "cvv", "pin"],
     "Never share your OTP, CVV, or PIN with anyone — not your bank, not a caller "
     "claiming to be support staff, nobody. Legitimate banks and companies never ask "
     "for these over call, SMS, or email."),
    (["job", "work from home", "salary"],
     "Be cautious of job offers that promise very high pay for minimal work and ask you "
     "to pay a registration or training fee upfront. Legitimate employers never charge "
     "candidates to give them a job — verify through the company's official careers page."),
    (["report", "complain", "helpline"],
     "You can report cyber fraud in India via the National Cyber Crime Helpline (1930), "
     "the National Cybercrime Reporting Portal (cybercrime.gov.in), CERT-In "
     "(incident@cert-in.org.in) for technical incidents, or the RBI Ombudsman "
     "(cms.rbi.org.in) for banking fraud."),
    (["phishing", "email", "link"],
     "Phishing emails often use urgency, generic greetings like 'Dear Customer', and "
     "links to lookalike domains. Always check the sender's actual email address and "
     "hover over links before clicking — or better, go directly to the official website."),
    (["qr code", "qr"],
     "Scanning a QR code and entering your PIN authorises an OUTGOING payment, never an "
     "incoming one. Be very suspicious of any 'scan to receive cashback/refund' message."),
]

DEFAULT_CHAT_REPLY = (
    "I'm your AI cyber safety assistant. I can help you understand phishing emails, "
    "UPI/QR scams, fake job offers, OTP fraud, and how to report cybercrime in India. "
    "Feel free to paste a suspicious message in the Detect Scam section above, or ask me "
    "a question about staying safe online."
)


def _local_chat_reply(message: str) -> str:
    low = message.lower()
    for keywords, reply in CANNED_CHAT_RESPONSES:
        if any(k in low for k in keywords):
            return reply
    return DEFAULT_CHAT_REPLY


@app.route("/api/chat", methods=["POST"])
def api_chat():
    body = request.get_json(silent=True) or {}
    message = (body.get("message") or "").strip()
    session_id = body.get("session_id") or str(uuid.uuid4())

    if not message:
        return jsonify({"error": "Message is required."}), 400

    history = CHAT_SESSIONS.setdefault(session_id, [])
    history.append({"role": "user", "content": message})

    reply = None
    if watsonx_client.is_configured():
        try:
            prompt = _build_chat_prompt(history)
            reply = watsonx_client.generate(prompt, max_new_tokens=250, temperature=0.5)
        except Exception as e:
            log.warning("watsonx.ai chat generation failed, using fallback: %s", e)

    if not reply:
        reply = _local_chat_reply(message)

    history.append({"role": "assistant", "content": reply})
    # Keep sessions bounded
    if len(history) > 20:
        CHAT_SESSIONS[session_id] = history[-20:]

    return jsonify({"reply": reply, "session_id": session_id})


def _build_chat_prompt(history):
    convo = "\n".join(f"{'User' if h['role']=='user' else 'Assistant'}: {h['content']}" for h in history[-6:])
    return (
        "You are the AI Cyber Assistant for AI ScamShield, a friendly and knowledgeable "
        "assistant that helps users in India understand and avoid online scams, phishing, "
        "UPI fraud, and cyber threats. Keep replies concise (3-5 sentences), practical, "
        "and reassuring.\n\n"
        f"{convo}\nAssistant:"
    )


# ══════════════════════════════════════════════════════════════════════════
# API: THREAT DASHBOARD
# ══════════════════════════════════════════════════════════════════════════
SCAM_TYPE_COLORS = {
    "Phishing Email": "#e74c3c",
    "UPI Fraud": "#e67e22",
    "Fake Job Offer": "#9b59b6",
    "Lottery / Prize Scam": "#f1c40f",
    "Malicious URL": "#3498db",
    "Banking / OTP Fraud": "#1abc9c",
    "QR Code Scam": "#e84393",
    "WhatsApp Scam": "#2ecc71",
    "No Specific Scam Pattern": "#95a5a6",
    "None Detected": "#95a5a6",
}

BASELINE_DISTRIBUTION = {
    "Phishing Email": 342, "UPI Fraud": 289, "Fake Job Offer": 176,
    "Lottery / Prize Scam": 154, "Malicious URL": 210, "Banking / OTP Fraud": 198,
    "QR Code Scam": 88, "WhatsApp Scam": 121,
}

TOP_THREATS_BASELINE = [
    {"rank": 1, "threat": "SBI KYC Suspension SMS Campaign", "severity": "HIGH", "reports": 1284},
    {"rank": 2, "threat": "Fake UPI Cashback Collect Requests", "severity": "HIGH", "reports": 967},
    {"rank": 3, "threat": "Work-From-Home Registration Fee Scam", "severity": "MEDIUM", "reports": 742},
    {"rank": 4, "threat": "Amazon Account Verification Phishing", "severity": "HIGH", "reports": 655},
    {"rank": 5, "threat": "KBC Lucky Draw Prize Scam", "severity": "MEDIUM", "reports": 519},
    {"rank": 6, "threat": "Electricity Bill QR Code Fraud", "severity": "LOW", "reports": 331},
]


@app.route("/api/threat-dashboard")
def api_threat_dashboard():
    _reset_stats_if_new_day()

    total_scans = 1547 + STATS["total_scans"]
    scams_detected = 832 + STATS["scams_detected"]
    phishing_blocked = 342 + STATS["phishing_blocked"]
    upi_flagged = 289 + STATS["upi_flagged"]
    urls_flagged = 210 + STATS["urls_flagged"]
    rate = round((scams_detected / total_scans) * 100, 1) if total_scans else 0

    distribution = dict(BASELINE_DISTRIBUTION)
    for k, v in STATS["by_type"].items():
        if k in ("None Detected", "No Specific Scam Pattern"):
            continue
        distribution[k] = distribution.get(k, 0) + v

    scam_type_distribution = [
        {"type": k, "count": v, "color": SCAM_TYPE_COLORS.get(k, "#7f8c8d")}
        for k, v in sorted(distribution.items(), key=lambda x: -x[1])
    ]

    # Weekly trend: last 7 days, deterministic pseudo-history + today's live count
    today = datetime.utcnow().date()
    weekly_trend = []
    base_pattern = [58, 71, 64, 80, 95, 110, 89]
    for i in range(6, -1, -1):
        day = today - timedelta(days=i)
        count = base_pattern[6 - i]
        if i == 0:
            count += STATS["scams_detected"]
        weekly_trend.append({"day": day.strftime("%a"), "scams": count})

    risk_level_breakdown = {
        "HIGH": 412 + STATS["by_risk"]["HIGH"],
        "MEDIUM": 298 + STATS["by_risk"]["MEDIUM"],
        "LOW": 187 + STATS["by_risk"]["LOW"],
        "SAFE": 650 + STATS["by_risk"]["SAFE"],
    }

    return jsonify({
        "threat_summary": {
            "total_scans_today": total_scans,
            "scams_detected_today": scams_detected,
            "phishing_blocked": phishing_blocked,
            "upi_scams_flagged": upi_flagged,
            "malicious_urls_found": urls_flagged,
            "scam_detection_rate": rate,
        },
        "scam_type_distribution": scam_type_distribution,
        "weekly_trend": weekly_trend,
        "risk_level_breakdown": risk_level_breakdown,
        "top_threats": TOP_THREATS_BASELINE,
    })


# ══════════════════════════════════════════════════════════════════════════
# API: AWARENESS TIPS
# ══════════════════════════════════════════════════════════════════════════
AWARENESS_TIPS = [
    {"icon": "shield-lock", "category": "Banking Safety", "title": "Banks Never Ask for OTP",
     "tip": "Your bank will never call, SMS, or email you asking for your OTP, CVV, or PIN. Treat any such request as fraud."},
    {"icon": "envelope-exclamation", "category": "Email Safety", "title": "Check the Sender Domain",
     "tip": "Always check the actual email address, not just the display name — phishing emails often use lookalike domains."},
    {"icon": "credit-card-2-front", "category": "UPI Safety", "title": "PIN is Only for Sending",
     "tip": "You only ever need your UPI PIN to SEND money. If a 'collect request' or 'refund' asks for your PIN, decline it."},
    {"icon": "link-45deg", "category": "Link Safety", "title": "Hover Before You Click",
     "tip": "Check where a link actually leads before clicking, and prefer typing the organisation's known website directly."},
    {"icon": "briefcase", "category": "Job Safety", "title": "Legitimate Jobs Don't Charge You",
     "tip": "No genuine employer will ask you to pay a registration or training fee to receive a job offer."},
    {"icon": "qr-code-scan", "category": "QR Safety", "title": "Scanning ≠ Receiving Money",
     "tip": "Scanning a QR code and entering your PIN authorises a payment OUT of your account, never into it."},
    {"icon": "whatsapp", "category": "Messaging Safety", "title": "Verify Unknown Contacts",
     "tip": "If an unknown number claims to be a relative in distress, call a known family number to verify before sending money."},
    {"icon": "person-badge", "category": "Identity Safety", "title": "Guard Your Aadhaar & PAN",
     "tip": "Never share your Aadhaar or PAN number with unsolicited callers or over unverified links."},
    {"icon": "telephone-x", "category": "Phone Safety", "title": "Hang Up and Call Back",
     "tip": "If a caller claims to be from your bank, hang up and call the number printed on your card instead."},
    {"icon": "gift", "category": "Prize Safety", "title": "You Can't Win What You Didn't Enter",
     "tip": "Any message claiming you won a lottery or contest you never entered is a scam, especially if it asks for a fee."},
    {"icon": "wifi", "category": "Network Safety", "title": "Avoid Public Wi-Fi for Banking",
     "tip": "Don't do banking or enter passwords over public/unsecured Wi-Fi networks."},
    {"icon": "shield-check", "category": "General Safety", "title": "Verify Independently",
     "tip": "Before acting on any urgent request involving money or credentials, verify it through an independent, official channel."},
]


@app.route("/api/awareness-tips")
def api_awareness_tips():
    count = request.args.get("count", default=6, type=int)
    count = max(1, min(count, len(AWARENESS_TIPS)))
    tips = random.sample(AWARENESS_TIPS, count)
    return jsonify({"tips": tips})


# ══════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_DEBUG", "1") == "1"
    log.info("AI ScamShield starting — watsonx.ai configured: %s", watsonx_client.is_configured())
    app.run(host="0.0.0.0", port=port, debug=debug)
